Attribute VB_Name = "CreateDB"
Option Explicit

'************************************************************
'************************************************************
'***                                                      ***
'***    Code Generated By: MDB Code Wizard ver. 1.0.6     ***
'***                   john@farrow.org                    ***
'***                                                      ***
'************************************************************
'************************************************************

'***NOTICE:***
'IN ORDER FOR THIS CODE TO WORK PROPERLY YOU MUST PROVIDE
'REFERENCE TO 'Microsoft DAO 2.5/3.51 Compatibility Library
Private DB as Database

Public Function Create_Database(strDBPath as String) As Boolean
'************************************************************
' Purpose: Creates a Microsoft Access Database with its      
'          Tables, Indexes, Queries and Relationships.       
'                                                            
' Inputs:                                                    
'   strDBPath:   path of the database to be created.         
'                                                            
' Returns: True/False value indicating if the creation       
'          process was successful.                           
'                                                            
' Database Details:                                          
'   DB Path: 'D:\0_FileLib\Data\SystemFileList.mdb'
'   DB File DateStamp: 21/05/02 11:36:50 AM
'************************************************************

    Dim TblDef as TableDef
    Dim QryDef as QueryDef

    On Error GoTo ERR_ROUTINE

    Set DB = DBEngine(0).CreateDataBase(strDBPath, dbLangGeneral, 0)

    'CREATE TABLE DEFINITIONS
    '=============================
    Create_TblDef_FileList
    Create_TblDef_Messages
    Create_TblDef_Subs

    'CREATE QUERY DEFINITIONS
    '=============================
    Create_QryDef_FileList_Query
    Create_QryDef_FileList_Query1

    'CREATE RELATIONSHIPS
    '=============================
    Create_Rship_000
    Create_Rship_001
    Create_Database = True
DB.Close
Set DB = Nothing
Exit Function

ERR_ROUTINE:
    Create_Database = False
    MsgBox Err.Number & vbCrLf & vbCrLf & Err.Description, vbCritical
End Function

Private Sub Create_TblDef_FileList
    Dim TblDef as TableDef
    Dim Fld as Field
    Dim Idx as Index

    'CREATE TABLE: FileList
    '=============================
    Set TblDef = DB.CreateTableDef("FileList")
    With TblDef
        .Attributes = 0
        .Connect = ""
        .SourceTableName = ""
        .ValidationRule = ""
        .ValidationText = ""

        'CREATE FIELD: FileID
        '=============================
        Set Fld = TblDef.CreateField("FileID", 4, 4)
        With Fld
            .Attributes = 17
            .DefaultValue = ""
            .OrdinalPosition = 1
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: FilePath
        '=============================
        Set Fld = TblDef.CreateField("FilePath", 10, 255)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 2
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileName
        '=============================
        Set Fld = TblDef.CreateField("FileName", 10, 255)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 3
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileType
        '=============================
        Set Fld = TblDef.CreateField("FileType", 2, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 4
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileSuffix
        '=============================
        Set Fld = TblDef.CreateField("FileSuffix", 10, 3)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 5
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileLevel
        '=============================
        Set Fld = TblDef.CreateField("FileLevel", 3, 2)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 6
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileSize
        '=============================
        Set Fld = TblDef.CreateField("FileSize", 7, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 7
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileVersion
        '=============================
        Set Fld = TblDef.CreateField("FileVersion", 10, 20)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 8
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileCreateDate
        '=============================
        Set Fld = TblDef.CreateField("FileCreateDate", 8, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 9
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileAccessDate
        '=============================
        Set Fld = TblDef.CreateField("FileAccessDate", 8, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 10
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileModifyDate
        '=============================
        Set Fld = TblDef.CreateField("FileModifyDate", 8, 8)
        With Fld
            .Attributes = 1
            .DefaultValue = ""
            .OrdinalPosition = 11
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: StatusID
        '=============================
        Set Fld = TblDef.CreateField("StatusID", 3, 2)
        With Fld
            .Attributes = 1
            .DefaultValue = 1
            .OrdinalPosition = 12
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Checked
        '=============================
        Set Fld = TblDef.CreateField("Checked", 2, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 13
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE INDEX: Checked
        '=============================
        Set Idx = TblDef.CreateIndex("Checked")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("Checked")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileCreateDate
        '=============================
        Set Idx = TblDef.CreateIndex("FileCreateDate")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileCreateDate")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileCreateDate1
        '=============================
        Set Idx = TblDef.CreateIndex("FileCreateDate1")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileAccessDate")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileCreateDate2
        '=============================
        Set Idx = TblDef.CreateIndex("FileCreateDate2")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileModifyDate")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileID
        '=============================
        Set Idx = TblDef.CreateIndex("FileID")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileLevel
        '=============================
        Set Idx = TblDef.CreateIndex("FileLevel")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileLevel")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileName
        '=============================
        Set Idx = TblDef.CreateIndex("FileName")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileName")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FilePath
        '=============================
        Set Idx = TblDef.CreateIndex("FilePath")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FilePath")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileSize
        '=============================
        Set Idx = TblDef.CreateIndex("FileSize")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileSize")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileSize1
        '=============================
        Set Idx = TblDef.CreateIndex("FileSize1")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileVersion")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileSuffix
        '=============================
        Set Idx = TblDef.CreateIndex("FileSuffix")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileSuffix")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileType
        '=============================
        Set Idx = TblDef.CreateIndex("FileType")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileType")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: PrimaryKey
        '=============================
        Set Idx = TblDef.CreateIndex("PrimaryKey")
        With Idx
            .Clustered = False
            .Primary = True
            .Required = True
            .Unique = True
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: StatusID
        '=============================
        Set Idx = TblDef.CreateIndex("StatusID")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("StatusID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx
    End With

    DB.TableDefs.Append TblDef

    Set Fld = Nothing
    Set Idx = Nothing
    Set TblDef = Nothing
End Sub

Private Sub Create_TblDef_Messages
    Dim TblDef as TableDef
    Dim Fld as Field
    Dim Idx as Index

    'CREATE TABLE: Messages
    '=============================
    Set TblDef = DB.CreateTableDef("Messages")
    With TblDef
        .Attributes = 0
        .Connect = ""
        .SourceTableName = ""
        .ValidationRule = ""
        .ValidationText = ""

        'CREATE FIELD: MessageID
        '=============================
        Set Fld = TblDef.CreateField("MessageID", 4, 4)
        With Fld
            .Attributes = 17
            .DefaultValue = ""
            .OrdinalPosition = 1
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileID
        '=============================
        Set Fld = TblDef.CreateField("FileID", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 2
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: MessageTxt
        '=============================
        Set Fld = TblDef.CreateField("MessageTxt", 10, 255)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 3
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: StatusID
        '=============================
        Set Fld = TblDef.CreateField("StatusID", 3, 2)
        With Fld
            .Attributes = 1
            .DefaultValue = 1
            .OrdinalPosition = 4
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Checked
        '=============================
        Set Fld = TblDef.CreateField("Checked", 2, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 5
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE INDEX: Checked
        '=============================
        Set Idx = TblDef.CreateIndex("Checked")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("Checked")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileID
        '=============================
        Set Idx = TblDef.CreateIndex("FileID")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: PrimaryKey
        '=============================
        Set Idx = TblDef.CreateIndex("PrimaryKey")
        With Idx
            .Clustered = False
            .Primary = True
            .Required = True
            .Unique = True
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("MessageID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: ProjID
        '=============================
        Set Idx = TblDef.CreateIndex("ProjID")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("MessageID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: StatusID
        '=============================
        Set Idx = TblDef.CreateIndex("StatusID")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("StatusID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx
    End With

    DB.TableDefs.Append TblDef

    Set Fld = Nothing
    Set Idx = Nothing
    Set TblDef = Nothing
End Sub

Private Sub Create_TblDef_Subs
    Dim TblDef as TableDef
    Dim Fld as Field
    Dim Idx as Index

    'CREATE TABLE: Subs
    '=============================
    Set TblDef = DB.CreateTableDef("Subs")
    With TblDef
        .Attributes = 0
        .Connect = ""
        .SourceTableName = ""
        .ValidationRule = ""
        .ValidationText = ""

        'CREATE FIELD: SubID
        '=============================
        Set Fld = TblDef.CreateField("SubID", 4, 4)
        With Fld
            .Attributes = 17
            .DefaultValue = ""
            .OrdinalPosition = 1
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: FileID
        '=============================
        Set Fld = TblDef.CreateField("FileID", 4, 4)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 2
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: SubName
        '=============================
        Set Fld = TblDef.CreateField("SubName", 10, 150)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 3
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: SubType
        '=============================
        Set Fld = TblDef.CreateField("SubType", 10, 1)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 4
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: SubScope
        '=============================
        Set Fld = TblDef.CreateField("SubScope", 10, 1)
        With Fld
            .Attributes = 2
            .DefaultValue = ""
            .OrdinalPosition = 5
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
            .AllowZeroLength = False
        End With
        .Fields.Append Fld

        'CREATE FIELD: StatusID
        '=============================
        Set Fld = TblDef.CreateField("StatusID", 3, 2)
        With Fld
            .Attributes = 1
            .DefaultValue = 1
            .OrdinalPosition = 6
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE FIELD: Checked
        '=============================
        Set Fld = TblDef.CreateField("Checked", 2, 1)
        With Fld
            .Attributes = 1
            .DefaultValue = 0
            .OrdinalPosition = 7
            .Required = False
            .ValidationRule = ""
            .ValidationText = ""
        End With
        .Fields.Append Fld

        'CREATE INDEX: Checked
        '=============================
        Set Idx = TblDef.CreateIndex("Checked")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("Checked")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: FileID
        '=============================
        Set Idx = TblDef.CreateIndex("FileID")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("FileID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: PrimaryKey
        '=============================
        Set Idx = TblDef.CreateIndex("PrimaryKey")
        With Idx
            .Clustered = False
            .Primary = True
            .Required = True
            .Unique = True
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("SubID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: StatusID
        '=============================
        Set Idx = TblDef.CreateIndex("StatusID")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("StatusID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: SubID
        '=============================
        Set Idx = TblDef.CreateIndex("SubID")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("SubID")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: SubScope
        '=============================
        Set Idx = TblDef.CreateIndex("SubScope")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("SubScope")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: SubType
        '=============================
        Set Idx = TblDef.CreateIndex("SubType")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("SubType")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx

        'CREATE INDEX: SunName
        '=============================
        Set Idx = TblDef.CreateIndex("SunName")
        With Idx
            .Clustered = False
            .Primary = False
            .Required = False
            .Unique = False
            .IgnoreNulls = False
            Set Fld = Idx.CreateField("SubName")
                Fld.Attributes = 0
            .Fields.Append Fld
        End With
        .Indexes.Append Idx
    End With

    DB.TableDefs.Append TblDef

    Set Fld = Nothing
    Set Idx = Nothing
    Set TblDef = Nothing
End Sub

Private Sub Create_QryDef_FileList_Query
    Dim QryDef as QueryDef
    Dim SQL as String

    SQL = "UPDATE FileList SET FilePath = lcase(FilePath), Fi" & _
          "leName = lcase(FileName);"

    Set QryDef = DB.CreateQueryDef("FileList Query", SQL)

    SQL = ""
    Set QryDef = Nothing
End Sub

Private Sub Create_QryDef_FileList_Query1
    Dim QryDef as QueryDef
    Dim SQL as String

    SQL = "SELECT DISTINCTROW [FileList].[FileID], [FileList]" & _
          ".[FilePath], [FileList].[FileName], [Subs].[SubID]" & _
          ", [Subs].[SubName], [Subs].[SubType], [Subs].[SubS" & _
          "cope], [Subs].[StatusID], [Subs].[Checked] FROM Fi" & _
          "leList INNER JOIN Subs ON [FileList].[FileID] =[Su" & _
          "bs].[FileID];"

    Set QryDef = DB.CreateQueryDef("FileList Query1", SQL)

    SQL = ""
    Set QryDef = Nothing
End Sub

Private Sub Create_Rship_000
    Dim RShip as Relation
    Dim Fld as Field

    Set RShip = DB.CreateRelation("FileListMessages", "FileList", "Messages", 4352)

    RShip.Fields.Append RShip.CreateField("FileID")
    Rship.Fields("FileID").ForeignName = "FileID"

    DB.Relations.Append RShip
    Set Rship = Nothing
End Sub

Private Sub Create_Rship_001
    Dim RShip as Relation
    Dim Fld as Field

    Set RShip = DB.CreateRelation("FileListSubs", "FileList", "Subs", 4352)

    RShip.Fields.Append RShip.CreateField("FileID")
    Rship.Fields("FileID").ForeignName = "FileID"

    DB.Relations.Append RShip
    Set Rship = Nothing
End Sub
